### ISSUE TITLE
Is the principle about behavior towards each other appropriate?

### ISSUE THREAD

**Issue by fienen** [DrunkenUX/web-ethics-commitment#10]
> 6. I understand all designers or developers have varying levels of experience and exposure to certain techniques, technologies, and tools, and will not demean or belittle them for seeking out answers

The question has been raised if this makes sense as a principle, when all the other first draft items direct the behavior of the individual towards the user, rather than the individual towards their peers. While there's no question that we should treat each other with respect and kindness, and understand different experience levels, does this make sense to include in the bubble of outlining how we execute our trade ethically?

Alternatively, is there a rewording of the issue that might also make it align better in spirit with the other suggestions?

**Comment by AmirAsghary** [comment]
I don't believe the web-ethics commitment should be limited to dev-user relationships. So I think it should stay. However, since every other commitment starts with "I will", this one would need to start with it as well for better consistency. 
Maybe something like: "I will treat my peers and customers with respect and will not belittle them for seeking out answers" ?
